name: GitHub Actions
on: [create, push]
jobs:
  ci:
    name: Continuous integration
    runs-on: ubuntu-latest
    env:
      PGPASSWORD: foobar
    services:
      postgres:
        image: postgis/postgis
        env:
          POSTGRES_PASSWORD: foobar
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      rabbitmq:
        image: rabbitmq
      redis:
        image: redis
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Lint
      run: |
        psql -h localhost -U postgres -c "CREATE DATABASE scoutbee_server" && psql -h localhost -U postgres -c "DROP DATABASE scoutbee_server"
        psql -h localhost -U postgres -c "CREATE DATABASE scoutbee_server" && python manage.py makemigrations --dry-run --check
    # sudo -u postgres createdb scoutbee_server && python manage.py migrate && sudo -u postgres dropdb scoutbee_server
    # sudo -u postgres createdb scoutbee_server && python manage.py makemigrations --dry-run --check
